# Generated by Django 4.2.7 on 2023-11-05 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('par', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField(blank=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('players', models.ManyToManyField(to='golf_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.game')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.hole')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf_app.player')),
            ],
            options={
                'unique_together': {('player', 'game', 'hole')},
            },
        ),
    ]
