# Generated by Django 4.2.7 on 2023-11-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.RemoveField(
            model_name='score',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.DeleteModel(
            name='Hole',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
