# Generated by Django 4.2.7 on 2023-11-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playergamescore',
            unique_together=set(),
        ),
    ]
