# Generated by Django 4.2.7 on 2023-11-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0002_alter_score_unique_together_remove_score_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='handicap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
