# Generated by Django 4.2.7 on 2023-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0002_alter_playergamescore_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamescore',
            name='score',
        ),
        migrations.AddField(
            model_name='playergamescore',
            name='scores',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
